# Generated by Django 5.1.5 on 2026-06-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='memorization_target',
            field=models.CharField(choices=[('half_page', 'نصف صفحة'), ('one_page', 'صفحة كاملة'), ('two_pages', 'صفحتان'), ('quarter_juz', 'ربع حزب'), ('half_juz', 'نصف حزب'), ('juz', 'جزء كامل')], default='one_page', max_length=20, verbose_name='ورد الحفظ الثابت'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='revision_target',
            field=models.CharField(choices=[('half_page', 'نصف صفحة'), ('one_page', 'صفحة كاملة'), ('two_pages', 'صفحتان'), ('quarter_juz', 'ربع حزب'), ('half_juz', 'نصف حزب'), ('juz', 'جزء كامل')], default='one_page', max_length=20, verbose_name='ورد المراجعة الثابت'),
        ),
    ]
