# Generated by Django 5.1.5 on 2026-06-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=10)),
                ('memorization', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('excused', 'Excused')], max_length=10)),
                ('revision', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('excused', 'Excused')], max_length=10)),
                ('grade', models.PositiveIntegerField(default=0)),
                ('behavior', models.CharField(choices=[('good', 'Good'), ('average', 'Average'), ('weak', 'Weak')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
