# Generated by Django 5.1.5 on 2026-06-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrecord',
            old_name='grade',
            new_name='memorization_grade',
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='revision_grade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='behavior',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('stable', 'Stable'), ('needs_guidance', 'Needs Guidance')], max_length=20),
        ),
    ]
