# Generated by Django 5.1.5 on 2026-06-20 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_rename_grade_dailyrecord_memorization_grade_and_more'),
        ('students', '0002_remove_studentprofile_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyrecord',
            unique_together={('student', 'date')},
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='behavior_grade',
            field=models.CharField(choices=[('A+', 'ممتاز'), ('A', 'جيد جداً'), ('B', 'جيد'), ('C', 'مقبول'), ('D', 'ضعيف')], default='A+', max_length=5, verbose_name='تقييم السلوك اليومي'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='memorization_status',
            field=models.CharField(choices=[('yes', 'نعم (أكمله كاملاً)'), ('most', 'أغلبه'), ('little', 'قليلاً منه'), ('no', 'لا (لم يسمّع/يراجع شيء)')], default='yes', max_length=10, verbose_name='هل سمع الورد المحدد؟'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='memorization_surah',
            field=models.CharField(blank=True, choices=[('الفاتحة', '1. الفاتحة'), ('البقرة', '2. البقرة'), ('آل عمران', '3. آل عمران'), ('النساء', '4. النساء'), ('المائدة', '5. المائدة'), ('الأنعام', '6. الأنعام'), ('الناس', '114. الناس')], max_length=50, null=True, verbose_name='سورة الحفظ'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='revision_status',
            field=models.CharField(choices=[('yes', 'نعم (أكمله كاملاً)'), ('most', 'أغلبه'), ('little', 'قليلاً منه'), ('no', 'لا (لم يسمّع/يراجع شيء)')], default='yes', max_length=10, verbose_name='هل راجع الورد المحدد؟'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='revision_surah',
            field=models.CharField(blank=True, choices=[('الفاتحة', '1. الفاتحة'), ('البقرة', '2. البقرة'), ('آل عمران', '3. آل عمران'), ('النساء', '4. النساء'), ('المائدة', '5. المائدة'), ('الأنعام', '6. الأنعام'), ('الناس', '114. الناس')], max_length=50, null=True, verbose_name='سورة المراجعة'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='attendance',
            field=models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('excused', 'مستأذن')], default='present', max_length=10),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='memorization_grade',
            field=models.CharField(blank=True, choices=[('A+', 'ممتاز'), ('A', 'جيد جداً'), ('B', 'جيد'), ('C', 'مقبول'), ('D', 'ضعيف')], max_length=5, null=True, verbose_name='تقييم الحفظ'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات المعلم'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='revision_grade',
            field=models.CharField(blank=True, choices=[('A+', 'ممتاز'), ('A', 'جيد جداً'), ('B', 'جيد'), ('C', 'مقبول'), ('D', 'ضعيف')], max_length=5, null=True, verbose_name='تقييم المراجعة'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='behavior',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='memorization',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='revision',
        ),
    ]
